spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /test_db # 콘솔의 경로
  datasource:
    driver-class-name: org.h2.Driver # h2 드라이버 설정
    url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/test_db;AUTO_SERVER=TRUE # 접속 URL
    username: test # 사용자 이름
    password: 1234 # 사용자 암호
#    data: classpath:data-h2.sql # 시작할 때 실행시킬 script